### ISSUE TITLE
Implementation of Metrics

### ISSUE THREAD

**Issue by Aithu-Snehith** [DinoMan/speech-driven-animation#53]
I am trying to implement your model. I have read your paper and would like to know more information provided related to the implementation of the metrics.

1. Could you please provide info related to how you have implemented the metrics that are mentioned in the paper?

2. In few metrics like SNR and SSIM, With which image will the generated frame is compared with to get the measures of metrics? Is it with the given reference image for all the generated frames?

3.  it would be really helpful if could you please provide the formulas used for the metrics or the sudo codes.

Thanks

**Comment by DinoMan** [comment]
PSNR and SSIM are well-established full reference metrics in image processing. They are full reference metrics which means that they compare frames to the ground truth (corresponding frames). There are likely many implementations already available in python. The formula for PSNR is described [here](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio#:~:text=Peak%20signal%2Dto%2Dnoise%20ratio%2C%20often%20abbreviated%20PSNR%2C,the%20fidelity%20of%20its%20representation.). 

To calculate SSIM I think I used [this](https://scikit-image.org/docs/dev/auto_examples/transform/plot_ssim.html) function from the scikit library.

I measure PSNR on the whole video rather than on individual frames as stated here:  https://in.mathworks.com/matlabcentral/fileexchange/12455-psnr-of-yuv-videos.

The cpbd metrics also is [implemented](https://pypi.org/project/cpbd/) in python.

My blink detector repo is available [here](https://github.com/DinoMan/blink-detector)

I used a pretrained version of lipnet to perform lipreading.

**Comment by ry85** [comment]
Hi,
I am getting the below error while running the code:

/opt/conda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
out=out, **kwargs)
/opt/conda/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)

can you please help.
