### ISSUE TITLE
Is it just me?

### ISSUE THREAD

**Issue by illtellyoulater** [DinoMan/speech-driven-animation#67]
I know this is all open source, but... don't you guys think the result quality here is far from being even remotely usable?
Or is it just me? I've just tried making some videos using the provided models, and well... what's the point if not even the example image can produce a good result ?

**Comment by DinoMan** [comment]
Hi, the example should work just fine. How are you running the code? Also, the library should work well on all examples from the GRID, CREMA-D and TCD TIMIT datasets when using the corresponding pre-trained models but those models will not generalize to unseen faces since they are trained on datasets with too few identities. We have not released the model trained on LRW which can generalize to unseen faces.
